# Generated by Django 3.0 on 2021-07-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='descOneLine',
            field=models.TextField(default='defaultval', max_length=100),
            preserve_default=False,
        ),
    ]
