# Generated by Django 3.0 on 2021-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_movie_desconeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='descOneLine',
            field=models.TextField(max_length=200),
        ),
    ]
